### ISSUE TITLE
PasswordHistory.password CharField max_length should be 255, not 256, for db compability sake (Mainly MySQL)

### ISSUE THREAD

**Issue by ciarancourtney** [fizista/django-password-validators#1]
https://github.com/fizista/django-password-validators/blob/master/django_password_validators/password_history/models.py#L74

I got an error when using a default MySQL56 db from RDS that I couldn't recreate on a local MySQL install, most likley due to UTF8 collation type:

    django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

Looking online it seems the general consensis is to use max_length=255 for CharFields:

https://docs.djangoproject.com/en/1.11/ref/databases/#character-fields
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by fizista** [comment]
You're right. Corrected in the new version.
