### ISSUE TITLE
Error in Documentation: Wrong path for UniquePasswordsValidator 

### ISSUE THREAD

**Issue by Danane84** [fizista/django-password-validators#10]
Thanks for this neat little package, it helps me a lot whith the development of my own app. However, i think I found a bug: I just installed your package and while testing the functionality of the UniquePasswordValidator I realized that the reference to the `password_validation.py` file is missing in the relevant part of the code in the docs. I think it should be 

```
AUTH_PASSWORD_VALIDATORS = [
    ...
    {
        'NAME': 'django_password_validators.password_history.password_validation.UniquePasswordsValidator',
    },
    ...
]
```
instead of 

```
AUTH_PASSWORD_VALIDATORS = [
    ...
    {
        'NAME': 'django_password_validators.password_history.UniquePasswordsValidator',
    },
    ...
]
```

However, when i corrected this in my settings.py, I got an error when I tried to set up a new user: 

```
Request Method: | POST
-- | --
http://localhost:8000/admin/users/customuser/add/
2.2.15
ProgrammingError
relation "password_history_userpasswordhistoryconfig" does not exist LINE 1: ...tory_userpasswordhistoryconfig"."iterations" FROM "password_...                                                              ^
/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute, line 84
/usr/local/bin/python
3.7.7
['/code',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Fri, 21 Aug 2020 08:58:22 +0000
```

I don't know if the above change causes some other issues somewhere in the code, but maybe you can have a look at it.

**Comment by fizista** [comment]
Run the migrations yet and then it should work.

And there was actually a problem with the documentation.

**Comment by fizista** [comment]
The problem has probably been fixed.

If there are problems, please reopen the report.
