### ISSUE TITLE
Add a number to limit password history lookup

### ISSUE THREAD

**Issue by spokerman12** [fizista/django-password-validators#17]
This is a frequently-used feature :)
Are there plans to implement it?
While this could be left out to manage through the database, it'd be cool to have over here.

**Comment by fizista** [comment]
I didn't plan to do that. 

But you can quickly write yourself something like this based on django code.

https://github.com/django/django/blob/master/django/contrib/auth/password_validation.py

You can also add this code to this library, after checking I will publish this new functionality.

**Comment by spokerman12** [comment]
The PR for this feature: https://github.com/fizista/django-password-validators/pull/18

**Comment by fizista** [comment]
I wrote a piece of code that implements your idea. It solves a couple of problems that still exist in your code. See if that's what you had in mind, and if it works well.

#19

**Comment by spokerman12** [comment]
@fizista looks great! Way cleaner than my proposal. Would you say that it's ready? I think it'd be nice to add some tests that take into account what happens if last_passwords is changed in the future.

**Comment by fizista** [comment]
Covered by tests I think I have all the problems. If I missed something, please write what tests need to be added.

**Comment by spokerman12** [comment]
Looks pretty good! @fizista. I've nothing else to add.

**Comment by fizista** [comment]
There is a new version on the PyPi server.

Thank you for your cooperation.
