### ISSUE TITLE
question - admin interface

### ISSUE THREAD

**Issue by millerthegorilla** [fizista/django-password-validators#20]
Hi, the app works well, but can I ask, what is the admin interface for?  Is it simply to delete password history for non active users?

Is there a way to hide it from the admin interface?

**Comment by fizista** [comment]
It can be used to delete any old password for a particular user.

To deactivate the panel it is probably enough to add such an entry in some file of your project:
```
admin.site.unregister(PasswordHistory)
```

**Comment by millerthegorilla** [comment]
@fizista   I have tried that and it doesn't work.  I get the following error:

```
admin.site.unregister(PasswordHistory)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 146, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model PasswordHistory is not registered
```

**Comment by millerthegorilla** [comment]
I also tried   admin.site.unregister(UserPasswordHistoryConfig), no luck.

**Comment by fizista** [comment]
It doesn't work for you because you are trying to unregister an unregistered admin panel.

Remember that the order of applications in the INSTALLED_APPS variable is important.

The order should be:

```
INSTALLED_APPS = [
   ...
    'django_password_validators.password_history',
   ...
    '<Your application where you unregister the admin panel>'
]
```

\<_Your application where you unregister the admin panel_\>/admin.py

```
from django_password_validators.password_history.models import PasswordHistory, UserPasswordHistoryConfig

from django.contrib import admin

admin.site.unregister(UserPasswordHistoryConfig)
admin.site.unregister(PasswordHistory)

```

And that's enough to disable this admin panel or any other panel.

**Comment by millerthegorilla** [comment]
Thanks for your help.  Works perfectly.  Cheers!
