### ISSUE TITLE
This password must contain at least 1 special character.

### ISSUE THREAD

**Issue by alex75311** [fizista/django-password-validators#23]
![image](https://user-images.githubusercontent.com/51674437/119054277-0ac5bf80-b9d0-11eb-8b87-c88de251870a.png)
![image](https://user-images.githubusercontent.com/51674437/119054341-2204ad00-b9d0-11eb-9926-9ce97e83739c.png)

**Comment by fizista** [comment]
What is the problem?

**Comment by alex75311** [comment]
for some reason does not apply settings from OPTIONS

**Comment by alex75311** [comment]
sorry i had a problem with the environment

**Comment by fizista** [comment]
It certainly works. On the test application it works. I checked a while ago.
