### ISSUE TITLE
Migration missing on password_history

### ISSUE THREAD

**Issue by Casassarnau** [fizista/django-password-validators#29]
When migrating my project with the password_history installed, says that a migration is missing on this app. Could you makemigrations and make a new release please? I'm running django-password-validators==1.7.0 with Django==4.0.8

**Comment by NoelJames** [comment]
I'm a little confused on the issue above and the PR that was created. 

On update to `1.7.0` I get a new migration like 
`/django_password_validators/password_history/migrations/0004_auto_20230228_2231.py`
    
Then, whenever I add a new instance (restart etc), work on another machine or update my environment. 
It creates the same one again like `/django_password_validators/password_history/migrations/password_history.0004_auto_20230228_2256.py`
 and again and again `/django_password_validators/password_history/migrations/0004_auto_20230228_2257.py`

(the migration is added to site-packages but, my environment changes)

I guess this has something to do with the migration not being in [migrations](https://github.com/fizista/django-password-validators/tree/v1.7.0/django_password_validators/password_history/migrations) dir with a constant name?
