### ISSUE TITLE
Incorrect password history message

### ISSUE THREAD

**Issue by Millz0r** [fizista/django-password-validators#36]
When a user tries to input one of his historical passwords he gets a message:

"You can not use a password that is already used in this application."

This message is confusing, as the password is not used in this application right now, but was used in the past. I suggest changing the message to:

"You can not use a password that was already used in this application in the past."

https://github.com/fizista/django-password-validators/blob/a76e19fa2da549e84b511b046a68fa218864cfda/django_password_validators/password_history/password_validation.py#L81

**Comment by wahabrind** [comment]
Or an ability to provide custom messages from settings.
